name: pastq
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.3+4005

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.0
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^9.1.0
  argon_buttons_flutter: ^1.0.6
  file_picker: ^3.0.3
  advance_pdf_viewer: ^2.0.0
  rflutter_alert: ^2.0.2
  flutter_typeahead: ^3.2.0
  flutter_svg: ^0.22.0

  #firebase plugins
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  firebase_storage: ^10.0.1
  cloud_firestore: ^2.4.0
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  
  uses-material-design: true

  assets:
    - assets/svg/
    - images/
  

  